### ISSUE TITLE
Support asynchronous execution of git-hook on Gina commit buffer

### ISSUE THREAD

**Issue by calebeby** [lambdalisue/gina.vim#115]
Hello,

I am using a pre-commit hook for linting. The linting takes ~2-3 seconds. When I use Gina to commit the changes, Gina blocks the editor while the hook is running. I think that instead, Gina should show the output of the hook. Is this something that you can implement?

Thanks for making this amazing project

**Comment by lambdalisue** [comment]
I have not enough experience with pre-commit hook. Could you create a sample project so that I can test the behavior? Calling `sleep xxx` instead of linting is enough

**Comment by calebeby** [comment]
https://github.com/calebeby/git-hooks-demo
Run `setup.sh` first which will symlink the hook file into the `.git/hooks` dir
Then try to commit (you can try from the command line too, just to see what it normally is like)

**Comment by calebeby** [comment]
Hi @lambdalisue,

Any chance you can implement this feature? I'd really appreciate it :smile: 

Thanks!

**Comment by lambdalisue** [comment]
Sorry. I'm a bit busy on this week so I haven't check it yet.

Keep ping me so that I don't forget about this while GitHub's issue notice is not really good for reminding....

2017年9月14日 12:27 +0900、Caleb Eby <notifications@github.com>のメール:

**Comment by lambdalisue** [comment]
@calebeby 

Sorry for late. Well, while gina requires to execute `git commit` to obtain an initial commit message, it is not possible to perform that command fully asynchronously (gina call `git commit` on `BufReadCmd`).
So I add `--no-verify` option for obtaining a message. So the 32398c6 won't call git-hook for obtaining a commit message but for actual commit.

Could you confirm if that implementation fix your problem?

**Comment by calebeby** [comment]
I would like it if gina.vim displayed the output from the precommit hook in a buffer. Can this be done?

**Comment by calebeby** [comment]
Because I still want my precommit hook to run, just not to freeze my editor

**Comment by calebeby** [comment]
Can you explain why `git commit` can't be run asynchronously?

**Comment by lambdalisue** [comment]
Technically, it is possible. However, the current gina's design doesn't accept asynchronous command execution on `modifiable` buffer.

Gina tried to follows Vim's flavor as much as possible.
That's why commands are executed in `BufReadCmd` (so that users can reload via `:e` and forcedly reload via `:e!`).

Some buffers (e.g. `gina-log`) updates its content asynchronously. However, while `gina-commit` is `modifiable`, all contents requires to be ready during `BufReadCmd` so that users can edit the content.

There are several options to implement such feature like

1. Call the command on `:Gina commit` and open the buffer after the command termination. I'm not really sure if it is a good idea while this implementation does not use `BufReadCmd`

2. Use `nomodifiable` during update like `gina-log` and change it to `modifiable` after all content has loaded. It seems fair enough but the implementation would become more complicated.

Currently, I don't have any trouble with git-hook while I've never use it.
So I don't have enough motivations to change the current design.

**Comment by calebeby** [comment]
OK, thanks for the explanation. I'll have to look into this more

**Comment by resolritter** [comment]
I think `no-verify` could be kept to make the editor not block while you're writing the commit message, and then run the pre-commit hooks asynchronously (in parallel) and wait the result. [There's this script which runs all pre-commit hooks](https://stackoverflow.com/a/55212685). That means QuitPre autocmd and other commands for executing "git commit" would be disabled until the result for that other job is received.

However, that is way more complicated than blocking. At the same time I find unacceptable that pre-commit hooks are ignored without telling the user. They are useful for ensuring the whole team is following code-styles before making the push, among other things.

I think having it enabled, even with blocking, makes more sense.

**Comment by lambdalisue** [comment]
Well, I don't use git-hooks so I don't have enough motivation for this. 
I'd love to check the idea or behavior as PRs 👍

**Comment by resolritter** [comment]
@lambdalisue since you don't use Git hooks, what do you think of reverting https://github.com/lambdalisue/gina.vim/commit/32398c63bc07421fb6ff0e718ad7012652098516? It won't make a difference for those not using hooks and it matches the default behavior of `git commit` better.

**Comment by lambdalisue** [comment]
Actually, that commit has not applied to master.

https://github.com/lambdalisue/gina.vim/blob/51a77c00db544b016878e292dba0368a69d69d88/autoload/gina/command/commit.vim#L409-L448

**Comment by resolritter** [comment]
@lambdalisue I see, sorry for the noise then! ^_^

**Comment by lambdalisue** [comment]
Too old
