### ISSUE TITLE
Request: Add a way to show an actual SHA1 on Gina blame

### ISSUE THREAD

**Issue by kristijanhusak** [lambdalisue/gina.vim#149]
Hi,

I have issue with showing proper sha for commit in git blame window.

This is how it looks using fugitive
![fugitive](https://i.imgur.com/QOwdgRg.png)

And this is what i get with gina with this format:
```vimL
let g:gina#command#blame#formatter#format = "%au - %in - %ma"
```
![gina](https://i.imgur.com/eJhGjbS.png)

it looks like it's just setting index of the commit from some array or something like that, not really sure.

I'm using latest NeoVim v0.2.3-dev on Linux Mint

**Comment by lambdalisue** [comment]
Currently, the `%in` need to be the last to make a correct SHA1 indicator (not documented sorry).

Or you can overwrite the syntax like

https://github.com/lambdalisue/gina.vim/blob/master/syntax/gina-blame.vim#L22-L26

**Comment by kristijanhusak** [comment]
Ok, but it looks like it's not working even if i leave the defaults:
![default](https://i.imgur.com/TmqLGhF.png)

**Comment by lambdalisue** [comment]
It seems to be working for me (I see the black bar). Don't you see the several color bars like the screenshots below?

https://github.com/lambdalisue/gina.vim/pull/45#issuecomment-283188984

**Comment by lambdalisue** [comment]
If you mean you cannot see the raw SHA1 hash, it's intentional ([ref](https://github.com/lambdalisue/gina.vim/blob/master/doc/gina.txt#L731))

I think the human cannot recognize the random string used in SHA1 so I replace that with color bars which indicates a single commit.

If you still need the SHA1, read https://github.com/lambdalisue/gina.vim/blob/master/doc/gina.txt#L809

**Comment by kristijanhusak** [comment]
Sure, but i believe there should be an option to show it with some custom formatter like you have on other parts of this line, at least first 8 chars, like fugitive do. I like to have it so i can copy it and inspect the commit directly from the terminal or browser, if i need more information. Is there a simple way to add it?

**Comment by lambdalisue** [comment]
I see. Actually, I'm planning to improve the custom formatting mech. on `Gina blame` before 1.0 so at that time, I'll add the way to show the SHA1. Additionally, I would like to hear what actually want to do with the SHA1 so that I may implement the alternative features for convenience.

> Is there a simple way to add it?

I'm sorry but no. If you would like to just see, you can use the example code in the help which I already told you. However, you need to hit `<Return>` to open a target commit to yank the actual commit for now.

Or if you desire, you can write a Vim script to get it programmatically like

```vim
let sha1_on_cursor = gina#action#candidates()[0].revision
```

but there is no (easy) way to use that value in the blame-navi window.

**Comment by kristijanhusak** [comment]
Ok, thanks. I'm just used to the fugitive way to access the sha, and i would like to have it here aswell when i switch.
