### ISSUE TITLE
A folder named `gina:` appears in my current working directory after invoking `:Gina diff`

### ISSUE THREAD

**Issue by kutsan** [lambdalisue/gina.vim#163]
As I mentioned in the title, typing `:Gina diff` or similar commands create this directory. I'm not sure why and I don't know if it's a bug or because of my configurations.

![image](https://user-images.githubusercontent.com/10108377/38470349-15719072-3b6a-11e8-96f8-e9b99d56ad9a.png)

**Comment by lambdalisue** [comment]
prob. your config. i guess you have a macro or so on to create a missing directory.

**Comment by lambdalisue** [comment]
https://github.com/lambdalisue/rook/blob/master/home/.config/nvim/init.vim 

in that case, ignore non file path. see line 398 of above link to find how

**Comment by kutsan** [comment]
Yeah you are right. I didn't investigate that much before, I had an macro similar to yours. Thanks!

**Comment by kutsan** [comment]
_Hate to leave without explain the solution._

I was using that macro like this,

https://github.com/kutsan/dotfiles/blob/793781692b08df6c0d56095a57c38b02cf644034/.vim/autoload/kutsan/autocmds.vim#L62-L73

I should have used `BufWritePre` event instead of `BufNewFile`.

**Comment by lambdalisue** [comment]
Well, I think it's a bit fragile.

The `BufNewFile` solves this problem because gina.vim does not use it, fortunately.
That means some other plugins may use that autocmd and you will get similar issue then.
So I recommend you to check the prefix of the `bufname` while Vim often uses a pseudo buffer like `ssh://xxxx`, `http://xxx` or so on and these pseudo buffers are not actual files.

**Comment by kutsan** [comment]
Thanks! I'll update accordingly.
