### ISSUE TITLE
Invalid document about action key (Tab is documented instead of a)

### ISSUE THREAD

**Issue by shinzui** [lambdalisue/gina.vim#203]
How do you get the `action:` prompt documented in the help? I tried hitting tab from a `gina-status` buffer, and I also tried hitting tab after opening the builtin help menu.

**Comment by lambdalisue** [comment]
Wow. I haven't noticed for while but the document is completely wrong 🙇 
You need to hit `a` (Action) instead of `<Tab>` from [this commit](https://github.com/lambdalisue/gina.vim/commit/3c195799e242cab3a542b36428d8862d2e71fe70).

Anyway, thank you for reporting. I'll fix the document then close this issue 👍

**Comment by ulidtko** [comment]
By the way, I'm really missing a `commit` action in the `gina-status` action menu :grin:

I'm aware I can configure this in my vimrc, but... it just feels that committing is one of the "hottest" actions in many workflows, and should be easily accessible by default.

**Comment by lambdalisue** [comment]
@ulidtko 

What kind of behavior is expected for `commit` action in `gina-status`? Just opening a `gina-commit` buffer or immediately commit picked changes with a short message via prompt?

**Anyway, it is a kind off-topic for this issue so please make a new issue for the reply or any feature requests 👍**
