### ISSUE TITLE
Gina blame text not helpful

### ISSUE THREAD

**Issue by prabirshrestha** [lambdalisue/gina.vim#51]
This is what I see when typing `:Gina blame :`. It is almost impossible to figure out what the text is.

![image](https://cloud.githubusercontent.com/assets/287744/23562985/9a96d68e-fff9-11e6-9c21-28e7b7445bca.png)

If I resize the window it shows the diff marker but doesn't do right align.

![image](https://cloud.githubusercontent.com/assets/287744/23563005/b6ff2466-fff9-11e6-88d3-4fdef0a70d95.png)

I'm using vim8 on windows.

**Comment by lambdalisue** [comment]
Thanks. But I could not reproduce the issue.

As I said, this is because the `gina-blame` buffer has numbers. So I guess some of your setting overwrite the `setlocal nonumber` in `ftplugin/gina-blame.vim`.

For workaround, you probably can use the following code to force `nonumber`

```
call gina#custom#execute('blame', 'setlocal nonumber')
```

But it should not be required. So could you make a minimal vimrc to reproduce the issue if you cannot find any code which overrule the `ftplugin/gina-blame.vim`?

**Comment by lambdalisue** [comment]
Or did you force `number` by purpose because you prefer? In that case, I'll think about how can I calculate the collect column length in that case.

**Comment by prabirshrestha** [comment]
I just have `set number` in my vimrc. If I comment that it works. Will try to get a repro with mimimal vimrc later today or tomorrow.

**Comment by lambdalisue** [comment]
So did you figure out the reason?

**Comment by prabirshrestha** [comment]
I'm closing this since after upgrading vim and all my plugins it seems to work correctly. Don't know what actually fixed the issue.

Sorry for the late response.

**Comment by lambdalisue** [comment]
Ok isee.
