### ISSUE TITLE
Window closed

### ISSUE THREAD

**Issue by carlitux** [lambdalisue/gina.vim#57]
If using terminal feature `Gina!! [command]` and more than one window, the focused window is removed.

**Comment by lambdalisue** [comment]
I see. I'll fix thanks

**Comment by lambdalisue** [comment]
Fixed.

**Comment by carlitux** [comment]
I just tried to test after long time(sorry):

```vim
:Gina commit " Allow enter the message but do not allow me put my password to sign the commit
:Gina! commit " echo the output
:Gina!! commit " open new tab and close without allowing set the message
```

**Comment by lambdalisue** [comment]
I'm sorry for late reply.

> " Allow enter the message but do not allow me put my password to sign the commit

It's a bit different problem. Does https://github.com/lambdalisue/gina.vim/blob/ab9c942187c184d3c76bd113677fcf2fceb7b5d4/doc/gina.txt#L2564-L2564 helps you?

**Comment by carlitux** [comment]
no, it doesn't when I call Gina! commit or Gina!! commit do nothing. Gina commit hangs on asking password.

**Comment by lambdalisue** [comment]
Ok. Probably I don't get your situation correctly.

1. Which Vim do you use? GVim, MacVim, Nvim-qt, Vim 8, Neovim, or whatever
2. What is your version of Vim?
3. What is your OS
4. Why do you need to use `:Gina! commit` or `:Gina!! commit` instead of `:Gina commit`?

Additionally, it sounds like the issue is a bug on Neovim if you are using neovim.

https://github.com/neovim/neovim/issues/1716

**Comment by carlitux** [comment]
@lambdalisue I am using neovim and I think that is the issue. thanks!!!
