### ISSUE TITLE
:Gina qrep! doesn't work

### ISSUE THREAD

**Issue by thinca** [lambdalisue/gina.vim#76]
Do:

```
:Gina qrep! foo
```

Result:

```
[gina] git: 'qrep!' is not a git command. See 'git --help'.
[gina]
[gina] Did you mean this?
[gina]  grep
```

**Comment by tracyone** [comment]
is grep not qrep

**Comment by thinca** [comment]
https://github.com/lambdalisue/gina.vim/blob/master/doc/gina.txt#L1546

**Comment by bimlas** [comment]
You're right: `Gina qrep` works for me, while `Gina qrep!` drops the same error.

It seems that [it checks if bang is present](https://github.com/lambdalisue/gina.vim/blob/d33352b086292603c01bde9410cc292c77d9c814/autoload/gina/command/qrep.vim#L36) and the [comparison](https://github.com/lambdalisue/gina.vim/blob/d33352b086292603c01bde9410cc292c77d9c814/autoload/gina/command/qrep.vim#L46) seems to work for me:

```viml
echo 'qrep!' =~# '!$'
" 1
echo 'qrep' =~# '!$'
" 0
```

I think Gina does not finds the autoload source of `qrep!` because of bang: I placed a "sign" on the beginning of qrep source.

```diff
diff --git a/autoload/gina/command/qrep.vim b/autoload/gina/command/qrep.vim
index 0d8d047..d41fc4a 100644
--- a/autoload/gina/command/qrep.vim
+++ b/autoload/gina/command/qrep.vim
@@ -3,8 +3,8 @@ let s:Path = vital#gina#import('System.Filepath')

 let s:SCHEME = gina#command#scheme(expand('<sfile>'))


 function! gina#command#qrep#call(range, args, mods) abort
+  echomsg 'OK'
   let git = gina#core#get_or_fail()
   let args = s:build_args(git, a:args)
```

`Gina qrep` prints "OK", but `Gina qrep!` doesn't, so it never reaching this line.

**Comment by bimlas** [comment]
Just found the [corresponding lines](https://github.com/lambdalisue/gina.vim/blob/d18d94cb0f3ee4c8db2fb121bd85f0c0a971202e/autoload/gina/command.vim#L9-L12): `gina#command#%s#call` ->`gina#command#qrep!#call` is not exists because of bang.
